// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelRating.Models;

namespace TravelRating.Migrations
{
    [DbContext(typeof(TravelRatingContext))]
    [Migration("20200401222203_User")]
    partial class User
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TravelRating.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.Property<string>("Token");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("TravelRating.Models.Experience", b =>
                {
                    b.Property<int>("ExperienceId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author")
                        .IsRequired();

                    b.Property<int>("LocationId");

                    b.Property<int>("Rating");

                    b.Property<string>("Review")
                        .IsRequired();

                    b.Property<int?>("UserId");

                    b.HasKey("ExperienceId");

                    b.HasIndex("LocationId");

                    b.HasIndex("UserId");

                    b.ToTable("Experiences");

                    b.HasData(
                        new
                        {
                            ExperienceId = 1,
                            Author = "Ben",
                            LocationId = 3,
                            Rating = 2,
                            Review = "Hanoi"
                        },
                        new
                        {
                            ExperienceId = 2,
                            Author = "Matt",
                            LocationId = 3,
                            Rating = 2,
                            Review = "Reykjavik"
                        },
                        new
                        {
                            ExperienceId = 3,
                            Author = "Katy",
                            LocationId = 3,
                            Rating = 2,
                            Review = "Kerry"
                        },
                        new
                        {
                            ExperienceId = 4,
                            Author = "Steph",
                            LocationId = 3,
                            Rating = 2,
                            Review = "New York"
                        });
                });

            modelBuilder.Entity("TravelRating.Models.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City")
                        .IsRequired();

                    b.Property<string>("Country")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("LocationId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            LocationId = 1,
                            City = "Hanoi",
                            Country = "Vietnam",
                            Name = "Ha Long Bay"
                        },
                        new
                        {
                            LocationId = 2,
                            City = "Reykjavik",
                            Country = "Iceland",
                            Name = "Thingvellir Park"
                        },
                        new
                        {
                            LocationId = 3,
                            City = "Kerry",
                            Country = "Ireland",
                            Name = "Killarney National Park"
                        },
                        new
                        {
                            LocationId = 4,
                            City = "New York",
                            Country = "United States",
                            Name = "Clock Walk"
                        });
                });

            modelBuilder.Entity("TravelRating.Models.Experience", b =>
                {
                    b.HasOne("TravelRating.Models.Location")
                        .WithMany("Experiences")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TravelRating.Entities.User", "User")
                        .WithMany("Experiences")
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
